apiVersion: v1
kind: Service
metadata:
  name: ratingsapi-service
  namespace: ash-workshop-dev
spec:
  selector:
    app: ratingsapi-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000    
  type: ClusterIP