apiVersion: v1
kind: Service
metadata:  
  name: nginx-svc
  namespace: ash-workshop-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pod
  type: ClusterIP