apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: ash-workshop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  strategy: {}
  template:
    metadata:      
      labels:
        app: nginx-pod
    spec:
      containers:
      - image: azcashacr.azurecr.io/nginx:alpine
        name: nginx-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "250Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: ash-acr-secret
      nodeSelector:
        agentpool: ashapipool
